SELECT /*+ MAX_EXECUTION_TIME(25000) */
DATE_FORMAT(DATE(DATE_SUB(DATE_LIV, INTERVAL 4 HOUR)), '%Y-%m-%d') AS evening,
FLOOR(MOD(HOUR(DATE_LIV)+8,24)*2 + MINUTE(DATE_LIV)/30) AS slot,
SOURCE_ID AS source_id, FLOOR_ID AS floor_id, CHUTE_NO AS chute,
COUNT(*) AS passages, COUNT(DISTINCT PARCEL_ID) AS distinct_parcels,
SUM(COALESCE(VOID,0)+0) AS voided
FROM parcel_history
WHERE DEPOT_ID=1 AND EXCEPTION=903 AND SOURCE_TYPE=200
AND DATE_LIV >= '2026-08-31 16:00:00' AND DATE_LIV < '2026-09-28 04:00:00'
AND (HOUR(DATE_LIV)>=16 OR HOUR(DATE_LIV)<4)
GROUP BY evening,slot,SOURCE_ID,FLOOR_ID,CHUTE_NO
ORDER BY evening,slot,SOURCE_ID,CHUTE_NO;
