SELECT /*+ MAX_EXECUTION_TIME(25000) */
DATE_FORMAT(DATE(DATE_SUB(DATE_LIV, INTERVAL 4 HOUR)), '%Y-%m-%d') AS evening,
FLOOR(MOD(HOUR(DATE_LIV)+8,24)*2 + MINUTE(DATE_LIV)/30) AS slot,
CHUTE_NO AS chute, COUNT(*) AS raw_rows,
COUNT(DISTINCT PARCEL_ID,DATE_LIV,COALESCE(CHUTE_NO,-1)) AS passages,
COUNT(DISTINCT PARCEL_ID) AS distinct_parcels
FROM parcel_history
WHERE DEPOT_ID=1 AND EXCEPTION=903 AND SOURCE_TYPE=200
AND (SOURCE_ID IS NULL OR SOURCE_ID=1) AND COALESCE(VOID,0)=0
AND DATE_LIV >= '2026-08-31 16:00:00' AND DATE_LIV < '2026-09-28 04:00:00'
AND (HOUR(DATE_LIV)>=16 OR HOUR(DATE_LIV)<4)
AND WEEKDAY(DATE_SUB(DATE_LIV,INTERVAL 4 HOUR))<5
GROUP BY evening,slot,CHUTE_NO ORDER BY evening,slot,CHUTE_NO;
